/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20Mock.sol";
export type { erc20MockSol };
import type * as stakeRelayerSol from "./StakeRelayer.sol";
export type { stakeRelayerSol };
export type { RewardChain } from "./RewardChain";
export type { StakeChain } from "./StakeChain";
