/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStakeChain,
  IStakeChainInterface,
} from "../../../contracts/StakeRelayer.sol/IStakeChain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "stakeChainSnapshot",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStakeChain__factory {
  static readonly abi = _abi;
  static createInterface(): IStakeChainInterface {
    return new Interface(_abi) as IStakeChainInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IStakeChain {
    return new Contract(address, _abi, runner) as unknown as IStakeChain;
  }
}
