/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRewardChain } from "./IRewardChain";
export type { IStakeChain } from "./IStakeChain";
export type { StakeRelayer } from "./StakeRelayer";
