/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StakeRelayerInterface extends Interface {
  getFunction(
    nameOrSignature: "relay" | "rewardChain" | "stakeChain"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "relay", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "rewardChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakeChain",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeChain", data: BytesLike): Result;
}

export interface StakeRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): StakeRelayer;
  waitForDeployment(): Promise<this>;

  interface: StakeRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  relay: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  rewardChain: TypedContractMethod<[], [string], "view">;

  stakeChain: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "relay"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardChain"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakeChain"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
