[package]
name = "soar-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.8.13"
alloy-sol-types.workspace = true
hex = "0.4.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sha3 = "0.10.8"
uint = "0.10.0"
